### PR TITLE
ci: Add appveyor integration

### LINKED ISSUE #78: Windows CI
AppVeyor seems to be the way people do this, and it is free for OSS. https://blog.markvincze.com/setting-up-an-appveyor-pipeline-for-golang/

### PR DESCRIPTION
**Pull request by keegancsmith**
Fixes #78

### CODE REVIEW

**Comment by alexsaveliev** [comment]
Awesome! With my pending changes (#86) test almost passes, failing only on `github.com/sourcegraph/go-langserver/langserver/internal/refs` which is works locally. Will keep investigating why, however LGTM to merge this PR

**Comment by keegancsmith** [comment]
@alexsaveliev cool :) I'll merge once we have code that works on windows, otherwise this will just complain on every PR.

**Comment by slimsag** [comment]
@alexsaveliev is this also rolled up into #133 ? can we close this PR?

**Comment by alexsaveliev** [comment]
@slimsag yes, these changes were integrated into #133. You may close this one

**Pull request closed without merging**
