### PR TITLE
Windows (updated)

### PR DESCRIPTION
**Pull request by lloiser**
This is basically a continuation of #133.

I merged master back in and fixed all failing tests.

This PR still depends on sourcegraph/ctxvfs#4

### CODE REVIEW

**Comment by saibing** [comment]
```go
// Root returns the RootURI if set, or otherwise the RootPath with 'file://' prepended.
func (p *InitializeParams) Root() DocumentURI {
	if p.RootURI != "" {
		return p.RootURI
	}
	return DocumentURI("file://" + p.RootPath)
}
```
Maybe need change as follow:

```go
// Root returns the RootURI if set, or otherwise the RootPath with 'file://' prepended.
func (p *InitializeParams) Root() DocumentURI {
	if p.RootURI != "" {
		return p.RootURI
	}
	if strings.HasPrefix(p.RootPath, "file://") {
		return DocumentURI(p.RootPath)
	}
	return DocumentURI("file://" + p.RootPath)
}
```

**Comment by keegancsmith** [comment]
Thanks so much for the update! I would like to closely review this, but won't have time for that this week. I'll take a look ASAP next week.

**Comment by lloiser** [comment]
There are still no appveyor builds... Is anything missing?

**Comment by keegancsmith** [comment]
Just enabled it. Manually enqueued and master is green https://ci.appveyor.com/project/sourcegraph/go-langserver/build/1

**Pull request merged**
