### PR TITLE
Windows support (WIP)

### PR DESCRIPTION
**Pull request by alexsaveliev**
- dealing with Windows-specific paths, converting them to Unix style. Depends on sourcegraph/ctxvfs#2. I'm leaving this PR here just in case of

### CODE REVIEW

**Comment by keegancsmith** [comment]
@alexsaveliev isn't the ctxvfs changes blocked at the moment? Do we have a plan to go forward / accept the PR as it stands?

**Comment by alexsaveliev** [comment]
@keegancsmith I have started a discussion in golang-nuts, will post a link once it will pass moderation. Then I'll see what is our plan based on the feedback :)

**Comment by keegancsmith** [comment]
Link here https://groups.google.com/forum/#!topic/golang-nuts/S_w53PDGR0I

**Comment by alexsaveliev** [comment]
Closing this in favor of #86

**Pull request closed without merging**
