### PR TITLE
fix references result is empty

### PR DESCRIPTION
**Pull request by Cosson2017**
fix references result is empty

### CODE REVIEW

**Comment by Cosson2017** [comment]
#229

**Comment by keegancsmith** [comment]
@Cosson2017 Sorry I missed this! I pushed an alternative fix. Does the latest master solve your problem?

**Comment by Cosson2017** [comment]
deepinscreenshot_select-area_20180222144657
I find h.init.RootImportPath is "" causes function pkgInWorkspace return false. And when I let pkgInWorkspace return true, reference list responsed is not empty.

**Comment by ramya-rao-a** [comment]
@keegancsmith I can attest to that. It definitely did work sometime last year when we added support to the language server in VS Code

**Pull request merged**
