### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by alexsaveliev**
This attempt to add Windows support is based on my initial proposal #86. I have tried to minimize number of changes required or at least make them in the same place where possible. 

PR can be described by the following statements:
 
- use special methods to compare paths or to relativize path taking into account possibility that arguments may use different separators and be or not be prefixed with slash (path-like and filepath-like arguments)
- use context's methods to work with the file system instead of `path` or `filepath` ones
- use `path` methods to extract dirnames and basenames instead of `filepath` ones because we are working with VFS-like paths mainly
- unfortunately, there still was a need to add OS-specific behavior because some objects which may use build context may pass OS-specific arguments

This PR contains changes merged from #79 to enable Appveyor integration
This PR depends on sourcegraph/ctxvfs#4

### CODE REVIEW

**Comment by slimsag** [comment]
Assign me and @keegancsmith when this is ready for review and we'll take a look BTW :)

**Comment by alexsaveliev** [comment]
@slimsag, @keegancsmith I don't have permissions to assign PRs in this repository, so pretty please with sugar on top :)
I have doubts regarding the last commit here (@f15a63a). It probably should be redone to move right things into the right packages instead of moving the whole utils.go

**Comment by keegancsmith** [comment]
Sorry for not taking a look at this sooner. Will review today.

**Comment by keegancsmith** [comment]
@alexsaveliev if you look at the conflicts you have introduced a `container` variables that is never used (only written to).

**Comment by mattn** [comment]
Any update on this?

**Comment by keegancsmith** [comment]
@mattn I don't have a windows box, but I can look into sorting out the merge conflicts and maybe you could test it?

**Comment by mattn** [comment]
I can test this (if conflict will be fixed). :+1:

**Comment by mattn** [comment]
@alexsaveliev Could you please rebase?

**Comment by keegancsmith** [comment]
@mattn I can rebase this, I just I believe the merge conflicts will be non-trivial. Finishing up some other work then will rebase this PR.

**Comment by mattn** [comment]
Any update on this?

**Comment by saibing** [comment]
This MR is very good, who can let it merge into master?

**Comment by slimsag** [comment]
Sorry for the delays here, we haven't had a chance to rebase this yet.

If anyone wants to beat us to it and resubmit this PR, we would be very happy 😄

**Pull request merged**
