### PR TITLE
loader: Always publish diagnostics

### PR DESCRIPTION
**Pull request by keegancsmith**
We want to give feedback to a user once they have fixed a type error.

Fixes https://github.com/sourcegraph/go-langserver/issues/23

### CODE REVIEW

**Comment by keegancsmith** [comment]
@uforic can you test this out on your editor which does the underlining to see if it works? I'm not 100% convinced it will due to our aggressive caching.

**Comment by uforic** [comment]
Hey @keegancsmith - Just tried out this branch, and here's a snippet from my console. I added an "a" to the end of Handler, and this is the output when I deleted the "a". You can see that the "didChange" message that is published has no "a" (i.e. is error free), and we don't get a publish diagnostic message.

I'm on commit 825ebd0dfb84e4e9d84a557699c52b141c859f3ev, and after I checked out the branch I ran `go install github.com/sourcegraph/go-langserver/langserver/cmd/langserver-go` and restarted Sublime.

Any thoughts? I fixed a bug in how changes are sent to the server so that we send them more often, if you do a git pull on the Sublime package you can pick it up.

```
2016-11-10 10:32:17,203: 140735156629504: DEBUG: Sending command: ['Content-Length: 4088', '', '{', '  "method": "textDocument/didChange", ', '  "jsonrpc": "2.0", ', '  "id": 75, ', '  "params": {', '    "contentChanges": [', '      {', '        "text": "package app\\n\\nimport (\\n\\t\\"io/ioutil\\"\\n\\t\\"log\\"\\n\\t\\"net/http\\"\\n\\n\\t\\"sourcegraph.com/sourcegraph/sourcegraph/app/internal\\"\\n\\t\\"sourcegraph.com/sourcegraph/sourcegraph/app/internal/oauth2client\\"\\n\\t\\"sourcegraph.com/sourcegraph/sourcegraph/app/internal/ui\\"\\n\\t\\"sourcegraph.com/sourcegraph/sourcegraph/app/router\\"\\n\\t\\"sourcegraph.com/sourcegraph/sourcegraph/pkg/auth\\"\\n\\t\\"sourcegraph.com/sourcegraph/sourcegraph/pkg/conf\\"\\n\\t\\"sourcegraph.com/sourcegraph/sourcegraph/pkg/csp\\"\\n\\t\\"sourcegraph.com/sourcegraph/sourcegraph/pkg/eventsutil\\"\\n\\t\\"sourcegraph.com/sourcegraph/sourcegraph/pkg/handlerutil\\"\\n\\t\\"sourcegraph.com/sourcegraph/sourcegraph/pkg/httptrace\\"\\n\\thttpapiauth \\"sourcegraph.com/sourcegraph/sourcegraph/services/httpapi/auth\\"\\n\\n\\t// Import for side effects.\\n\\t_ \\"sourcegraph.com/sourcegraph/sourcegraph/app/internal/redirects\\"\\n)\\n\\n// NewHandler returns a new app handler that uses the provided app\\n// router (or creates a new one if nil).\\nfunc NewHandler(r *router.Router) http.Handler {\\n\\tif r == nil {\\n\\t\\tr = router.New(nil)\\n\\t}\\n\\n\\tauth.InitSessionStore(conf.AppURL.Scheme == \\"https\\")\\n\\tvar mw []handlerutil.Middleware\\n\\tmw = append(mw, httpapiauth.AuthorizationMiddleware, auth.CookieMiddleware)\\n\\tmw = append(mw, eventsutil.AgentMiddleware)\\n\\tmw = append(mw, internal.Middleware...)\\n\\n\\tm := http.NewServeMux()\\n\\tif conf.GetenvBool(\\"SG_USE_CSP\\") {\\n\\t\\tcspHandler := csp.NewHandler(cspConfig)\\n\\t\\tcspHandler.ReportLog = log.New(ioutil.Discard, \\"\\", 0)\\n\\t\\tmw = append(mw, cspHandler.Middleware)\\n\\t}\\n\\n\\tm.Handle(\\"/\\", r)\\n\\n\\tr.Get(router.RobotsTxt).Handler(httptrace.TraceRoute(http.HandlerFunc(robotsTxt)))\\n\\tr.Get(router.Favicon).Handler(httptrace.TraceRoute(http.HandlerFunc(favicon)))\\n\\n\\tr.Get(router.SitemapIndex).Handler(httptrace.TraceRoute(internal.Handler(serveSitemapIndex)))\\n\\tr.Get(router.RepoSitemap).Handler(httptrace.TraceRoute(internal.Handler(serveRepoSitemap)))\\n\\n\\tr.Get(router.Logout).Handler(httptrace.TraceRoute(internal.Handler(serveLogout)))\\n\\n\\t// Redirects\\n\\tr.Get(router.OldToolsRedirect).Handler(httptrace.TraceRoute(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {\\n\\t\\thttp.Redirect(w, r, \\"/beta\\", 301)\\n\\t})))\\n\\n\\tr.Get(router.UI).Handler(ui.Router())\\n\\n\\tr.Get(router.GitHubOAuth2Initiate).Handler(httptrace.TraceRoute(internal.Handler(oauth2client.ServeGitHubOAuth2Initiate)))\\n\\tr.Get(router.GitHubOAuth2Receive).Handler(httptrace.TraceRoute(internal.Handler(oauth2client.ServeGitHubOAuth2Receive)))\\n\\tr.Get(router.GoogleOAuth2Initiate).Handler(httptrace.TraceRoute(internal.Handler(oauth2client.ServeGoogleOAuth2Initiate)))\\n\\tr.Get(router.GoogleOAuth2Receive).Handler(httptrace.TraceRoute(internal.Handler(oauth2client.ServeGoogleOAuth2Receive)))\\n\\n\\tr.Get(router.GDDORefs).Handler(httptrace.TraceRoute(internal.Handler(serveGDDORefs)))\\n\\n\\treturn handlerutil.WithMiddleware(m, mw...)\\n}\\n\\n// cspConfig is the Content Security Policy config for app handlers.\\nvar cspConfig = csp.Config{\\n\\t// Strict because API responses should never be treated as page\\n\\t// content.\\n\\tPolicyReportOnly: &csp.Policy{\\n\\t\\tDefaultSrc: []string{\\"\'self\'\\"},\\n\\t\\tFrameSrc:   []string{\\"https://www.youtube.com\\", \\"https://speakerdeck.com\\"},\\n\\t\\tFontSrc:    []string{\\"\'self\'\\", \\"https://s3-us-west-2.amazonaws.com/sourcegraph-assets/fonts/\\"},\\n\\t\\tScriptSrc:  []string{\\"\'self\'\\", \\"https://www.google-analytics.com\\", \\"https://platform.twitter.com\\", \\"https://speakerdeck.com\\"},\\n\\t\\tImgSrc:     []string{\\"*\\"},\\n\\t\\tStyleSrc:   []string{\\"*\\"},\\n\\t\\tReportURI:  \\"/.csp-report\\",\\n\\t},\\n}\\n\\nfunc serveLogout(w http.ResponseWriter, r *http.Request) error {\\n\\tauth.DeleteSession(w, r)\\n\\thttp.Redirect(w, r, \\"/\\", http.StatusFound)\\n\\treturn nil\\n}\\n"', '      }', '    ], ', '    "textDocument": {', '      "uri": "file:///Users/mattfs/gopath/src/sourcegraph.com/sourcegraph/sourcegraph/app/app.go", ', '      "version": 1', '    }', '  }', '}']
2016-11-10 10:32:17,204: 140735156629504: DEBUG: on_selection_modified
2016-11-10 10:32:17,204: 140735156629504: DEBUG: on_selection_modified_with_info
2016-11-10 10:32:17,204: 140735156629504: DEBUG: on_post_text_command
2016-11-10 10:32:17,201: 123145322901504: DEBUG: Read body of length: 37
2016-11-10 10:32:17,201: 123145322901504: DEBUG: Received raw data: {'result': {}, 'id': 74, 'jsonrpc': '2.0'}
2016-11-10 10:32:17,201: 123145322901504: DEBUG: Converted raw data: None
2016-11-10 10:32:17,203: 123145322901504: DEBUG: Read body of length: 37
2016-11-10 10:32:17,203: 123145322901504: DEBUG: Received raw data: {'result': {}, 'id': 75, 'jsonrpc': '2.0'}
2016-11-10 10:32:17,203: 123145322901504: DEBUG: Converted raw data: None
2016-11-10 10:32:17,305: 140735156629504: DEBUG: on_idle
2016-11-10 10:32:17,306: 140735156629504: DEBUG: Received order to post command: {"type": "request", "seq": 76, "arguments": {"files": ["/Users/mattfs/gopath/src/sourcegraph.com/sourcegraph/sourcegraph/app/app.go"], "delay": 500}, "command": "geterr"}
2016-11-10 10:32:18,455: 140735156629504: DEBUG: on_selection_idle
2016-11-10 10:32:18,456: 140735156629504: DEBUG: Received order to post command: {"type": "request", "seq": 77, "arguments": {"offset": 47, "file": "/Users/mattfs/gopath/src/sourcegraph.com/sourcegraph/sourcegraph/app/app.go", "line": 26}, "command": "quickinfo"}
2016-11-10 10:32:18,456: 140735156629504: DEBUG: Sending command: ['Content-Length: 283', '', '{', '  "method": "textDocument/hover", ', '  "jsonrpc": "2.0", ', '  "id": 77, ', '  "params": {', '    "position": {', '      "character": 46, ', '      "line": 25', '    }, ', '    "textDocument": {', '      "uri": "file:///Users/mattfs/gopath/src/sourcegraph.com/sourcegraph/sourcegraph/app/app.go"', '    }', '  }', '}']
2016-11-10 10:32:18,457: 140735156629504: DEBUG: Received order to post command: {"type": "request", "seq": 78, "arguments": {"offset": 47, "file": "/Users/mattfs/gopath/src/sourcegraph.com/sourcegraph/sourcegraph/app/app.go", "filesToSearch": ["/Users/mattfs/gopath/src/sourcegraph.com/sourcegraph/sourcegraph/app/app.go"], "line": 26}, "command": "documentHighlights"}
2016-11-10 10:32:19,922: 123145322901504: DEBUG: Read body of length: 37
2016-11-10 10:32:19,922: 123145322901504: DEBUG: Received raw data: {'result': {}, 'id': 77, 'jsonrpc': '2.0'}
2016-11-10 10:32:19,922: 123145322901504: DEBUG: Converted raw data: None
```

**Comment by uforic** [comment]
I can also get cases where there _is_ an error that is created and sent over in didChange, and there are no diagnostics published back. Here is a snippet example. I find I can replicate it when I type "a" at the end of handler, and immediately click off, creating a couple additional requests.

Video of it working (I don't click off): https://cl.ly/1i28301z0F2v
Video of it not working (after typing, I click off): https://cl.ly/1C3u3U1P1X0p


```
2016-11-10 10:42:48,014: 140735156629504: DEBUG: Sending command: ['Content-Length: 4089', '', '{', '  "id": 49, ', '  "jsonrpc": "2.0", ', '  "method": "textDocument/didChange", ', '  "params": {', '    "textDocument": {', '      "uri": "file:///Users/mattfs/gopath/src/sourcegraph.com/sourcegraph/sourcegraph/app/app.go", ', '      "version": 1', '    }, ', '    "contentChanges": [', '      {', '        "text": "package app\\n\\nimport (\\n\\t\\"io/ioutil\\"\\n\\t\\"log\\"\\n\\t\\"net/http\\"\\n\\n\\t\\"sourcegraph.com/sourcegraph/sourcegraph/app/internal\\"\\n\\t\\"sourcegraph.com/sourcegraph/sourcegraph/app/internal/oauth2client\\"\\n\\t\\"sourcegraph.com/sourcegraph/sourcegraph/app/internal/ui\\"\\n\\t\\"sourcegraph.com/sourcegraph/sourcegraph/app/router\\"\\n\\t\\"sourcegraph.com/sourcegraph/sourcegraph/pkg/auth\\"\\n\\t\\"sourcegraph.com/sourcegraph/sourcegraph/pkg/conf\\"\\n\\t\\"sourcegraph.com/sourcegraph/sourcegraph/pkg/csp\\"\\n\\t\\"sourcegraph.com/sourcegraph/sourcegraph/pkg/eventsutil\\"\\n\\t\\"sourcegraph.com/sourcegraph/sourcegraph/pkg/handlerutil\\"\\n\\t\\"sourcegraph.com/sourcegraph/sourcegraph/pkg/httptrace\\"\\n\\thttpapiauth \\"sourcegraph.com/sourcegraph/sourcegraph/services/httpapi/auth\\"\\n\\n\\t// Import for side effects.\\n\\t_ \\"sourcegraph.com/sourcegraph/sourcegraph/app/internal/redirects\\"\\n)\\n\\n// NewHandler returns a new app handler that uses the provided app\\n// router (or creates a new one if nil).\\nfunc NewHandler(r *router.Router) http.Handlera {\\n\\tif r == nil {\\n\\t\\tr = router.New(nil)\\n\\t}\\n\\n\\tauth.InitSessionStore(conf.AppURL.Scheme == \\"https\\")\\n\\tvar mw []handlerutil.Middleware\\n\\tmw = append(mw, httpapiauth.AuthorizationMiddleware, auth.CookieMiddleware)\\n\\tmw = append(mw, eventsutil.AgentMiddleware)\\n\\tmw = append(mw, internal.Middleware...)\\n\\n\\tm := http.NewServeMux()\\n\\tif conf.GetenvBool(\\"SG_USE_CSP\\") {\\n\\t\\tcspHandler := csp.NewHandler(cspConfig)\\n\\t\\tcspHandler.ReportLog = log.New(ioutil.Discard, \\"\\", 0)\\n\\t\\tmw = append(mw, cspHandler.Middleware)\\n\\t}\\n\\n\\tm.Handle(\\"/\\", r)\\n\\n\\tr.Get(router.RobotsTxt).Handler(httptrace.TraceRoute(http.HandlerFunc(robotsTxt)))\\n\\tr.Get(router.Favicon).Handler(httptrace.TraceRoute(http.HandlerFunc(favicon)))\\n\\n\\tr.Get(router.SitemapIndex).Handler(httptrace.TraceRoute(internal.Handler(serveSitemapIndex)))\\n\\tr.Get(router.RepoSitemap).Handler(httptrace.TraceRoute(internal.Handler(serveRepoSitemap)))\\n\\n\\tr.Get(router.Logout).Handler(httptrace.TraceRoute(internal.Handler(serveLogout)))\\n\\n\\t// Redirects\\n\\tr.Get(router.OldToolsRedirect).Handler(httptrace.TraceRoute(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {\\n\\t\\thttp.Redirect(w, r, \\"/beta\\", 301)\\n\\t})))\\n\\n\\tr.Get(router.UI).Handler(ui.Router())\\n\\n\\tr.Get(router.GitHubOAuth2Initiate).Handler(httptrace.TraceRoute(internal.Handler(oauth2client.ServeGitHubOAuth2Initiate)))\\n\\tr.Get(router.GitHubOAuth2Receive).Handler(httptrace.TraceRoute(internal.Handler(oauth2client.ServeGitHubOAuth2Receive)))\\n\\tr.Get(router.GoogleOAuth2Initiate).Handler(httptrace.TraceRoute(internal.Handler(oauth2client.ServeGoogleOAuth2Initiate)))\\n\\tr.Get(router.GoogleOAuth2Receive).Handler(httptrace.TraceRoute(internal.Handler(oauth2client.ServeGoogleOAuth2Receive)))\\n\\n\\tr.Get(router.GDDORefs).Handler(httptrace.TraceRoute(internal.Handler(serveGDDORefs)))\\n\\n\\treturn handlerutil.WithMiddleware(m, mw...)\\n}\\n\\n// cspConfig is the Content Security Policy config for app handlers.\\nvar cspConfig = csp.Config{\\n\\t// Strict because API responses should never be treated as page\\n\\t// content.\\n\\tPolicyReportOnly: &csp.Policy{\\n\\t\\tDefaultSrc: []string{\\"\'self\'\\"},\\n\\t\\tFrameSrc:   []string{\\"https://www.youtube.com\\", \\"https://speakerdeck.com\\"},\\n\\t\\tFontSrc:    []string{\\"\'self\'\\", \\"https://s3-us-west-2.amazonaws.com/sourcegraph-assets/fonts/\\"},\\n\\t\\tScriptSrc:  []string{\\"\'self\'\\", \\"https://www.google-analytics.com\\", \\"https://platform.twitter.com\\", \\"https://speakerdeck.com\\"},\\n\\t\\tImgSrc:     []string{\\"*\\"},\\n\\t\\tStyleSrc:   []string{\\"*\\"},\\n\\t\\tReportURI:  \\"/.csp-report\\",\\n\\t},\\n}\\n\\nfunc serveLogout(w http.ResponseWriter, r *http.Request) error {\\n\\tauth.DeleteSession(w, r)\\n\\thttp.Redirect(w, r, \\"/\\", http.StatusFound)\\n\\treturn nil\\n}\\n"', '      }', '    ]', '  }', '}']
2016-11-10 10:42:48,016: 140735156629504: DEBUG: on_selection_modified
2016-11-10 10:42:48,016: 140735156629504: DEBUG: on_selection_modified_with_info
2016-11-10 10:42:48,014: 123145322901504: DEBUG: Read body of length: 37
2016-11-10 10:42:48,015: 123145322901504: DEBUG: Received raw data: {'id': 49, 'jsonrpc': '2.0', 'result': {}}
2016-11-10 10:42:48,015: 123145322901504: DEBUG: Converted raw data: None
2016-11-10 10:42:48,043: 123145322901504: DEBUG: Read body of length: 37
2016-11-10 10:42:48,043: 123145322901504: DEBUG: Received raw data: {'id': 47, 'jsonrpc': '2.0', 'result': {}}
2016-11-10 10:42:48,043: 123145322901504: DEBUG: Converted raw data: None
2016-11-10 10:42:48,068: 140735156629504: DEBUG: on_query_completions
2016-11-10 10:42:48,069: 140735156629504: DEBUG: Received order to post command: {"type": "request", "seq": 50, "arguments": {"offset": 48, "file": "/Users/mattfs/gopath/src/sourcegraph.com/sourcegraph/sourcegraph/app/app.go", "line": 26, "prefix": "Handlera"}, "command": "completions"}
2016-11-10 10:42:48,116: 140735156629504: DEBUG: on_idle
2016-11-10 10:42:48,117: 140735156629504: DEBUG: Received order to post command: {"type": "request", "seq": 51, "arguments": {"delay": 500, "files": ["/Users/mattfs/gopath/src/sourcegraph.com/sourcegraph/sourcegraph/app/app.go"]}, "command": "geterr"}
2016-11-10 10:42:48,332: 140735156629504: DEBUG: on_text_command
2016-11-10 10:42:48,332: 140735156629504: DEBUG: on_text_command_with_info
2016-11-10 10:42:48,333: 140735156629504: DEBUG: on_selection_modified
2016-11-10 10:42:48,334: 140735156629504: DEBUG: on_selection_modified_with_info
2016-11-10 10:42:48,334: 140735156629504: DEBUG: on_post_text_command
2016-11-10 10:42:48,433: 140735156629504: DEBUG: on_selection_modified
2016-11-10 10:42:48,434: 140735156629504: DEBUG: on_selection_modified_with_info
2016-11-10 10:42:49,267: 140735156629504: DEBUG: on_selection_idle
2016-11-10 10:42:49,268: 140735156629504: DEBUG: Received order to post command: {"type": "request", "seq": 52, "arguments": {"offset": 1, "file": "/Users/mattfs/gopath/src/sourcegraph.com/sourcegraph/sourcegraph/app/app.go", "filesToSearch": ["/Users/mattfs/gopath/src/sourcegraph.com/sourcegraph/sourcegraph/app/app.go"], "line": 45}, "command": "documentHighlights"}
2016-11-10 10:42:54,703: 140735156629504: DEBUG: on_hover
```

**Comment by keegancsmith** [comment]
Nice, I didn't realise I could just use the sublime-ext as is to experiment. I think there are quite a few issues to clear up around caching/re-triggering typechecking on file changes. I won't be able to look into them this week more than likely, so just gonna close this out and un-assign myself. If this is an issue, lets chat about it :)

**Pull request closed without merging**
